company_name: Acme
content_table: true
item_name: Item
items_name: Items
paging_mode: paging
copyright_year: 2026
settings:
  categories_enabled: true
  companies_enabled: true
  tags_enabled: true
  surveys_enabled: true
  header:
    submit_enabled: true
    pricing_enabled: true
    layout_enabled: true
    language_enabled: true
    theme_enabled: true
    layout_default: home1
    pagination_default: standard
    theme_default: light
  homepage:
    hero_enabled: true
    search_enabled: true
    default_view: classic
    default_sort: popularity
  footer:
    subscribe_enabled: true
    version_enabled: true
    theme_selector_enabled: true
pagination:
  type: standard
  itemsPerPage: 12
custom_menu:
  header: []
  footer: []
version: 0.1.3
metadata:
  last_request_data:
    generation_method: create-update
    update_with_pull_request: false
    website_repository_creation_method: create-using-template
    name: Remote Team Tools
    prompt: Please one line description please. update all items to have one line
      descriptions, e.g Clockify
    providers:
      pipeline: agent-pipeline
      search: tavily
      ai: groq
      contentExtractor: local-content-extractor
    pluginConfig:
      target_keywords:
        - remote team tools
        - remote team tools
        - remote team tools
        - remote team tools
      capture_screenshots: false
    _processedPluginConfig: {}
  initial_prompt: Generate a directory of productivity apps for remote teams
  pr_update:
    branch: update-1770994532760
    title: Update data - 02/13/2026 14:55
    body: |-
      Update data for remote-team-tools

      Generated by [Ever Works](https://ever.works)
