company_name: Remote Team Tools
content_table: true
item_name: Item
items_name: Items
paging_mode: paging
copyright_year: 2026
settings:
  categories_enabled: true
  companies_enabled: false
  tags_enabled: true
  surveys_enabled: false
  header:
    submit_enabled: true
    pricing_enabled: false
    layout_enabled: true
    language_enabled: true
    theme_enabled: true
    layout_default: home2
    pagination_default: infinite
    theme_default: light
  homepage:
    hero_enabled: true
    search_enabled: true
    default_view: classic
    default_sort: popularity
  footer:
    subscribe_enabled: false
    version_enabled: false
    theme_selector_enabled: false
  collections_enabled: false
pagination:
  type: standard
  itemsPerPage: 12
custom_menu:
  header: []
  footer: []
version: 0.1.12
metadata:
  last_request_data:
    generation_method: create-update
    update_with_pull_request: false
    website_repository_creation_method: create-using-template
    name: Remote Team Tools
    prompt: Generate a directory of productivity apps for remote teams
    providers:
      pipeline: agent-pipeline
      search: jina
      ai: google
      contentExtractor: jina
    pluginConfig:
      target_keywords:
        - remote team tools
      capture_screenshots: false
      target_items: 50
      max_pages_to_process: 3
    _processedPluginConfig: {}
    config:
      max_search_queries: 10
      max_results_per_query: 5
      max_pages_to_process: 10
      ai_first_generation_enabled: false
  initial_prompt: Generate a directory of productivity apps for remote teams
  pr_update:
    branch: update-1770994532760
    title: Update data - 02/13/2026 14:55
    body: |-
      Update data for remote-team-tools

      Generated by [Ever Works](https://ever.works)
company_website: ""
